version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - [%(filename)s:%(lineno)d] - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  json:
    (): src.logging.json_formatter.JsonFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      module: module
      function: funcName
      line: lineno
handlers:
  stderr:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: ./logs/my_app.log.jsonl
    maxBytes: 500_000_000
    backupCount: 3
loggers:
  root:
    level: DEBUG
    handlers:
    - stderr
    - file